# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96be7cefd62a5a8a015c76c8a7e73169"
name = "fasdasfd"
application_url = "https://shop-form-nu.vercel.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://shop-form-nu.vercel.app/api/auth" ]

[build]
automatically_update_urls_on_dev = true
